export enum AppIcon {
  Progress = '/assets/icons/progress.svg',
  DailyLog = '/assets/icons/daily-log.svg',
  Kpi = '/assets/icons/kpi.svg',
  Menu = '/assets/icons/menu.svg',
  CheckCircle = '/assets/icons/check-circle.svg',
  ChevronRight = '/assets/icons/chevron-right.svg',
  Add = '/assets/icons/add.svg',
  ArrowBack = '/assets/icons/arrow-back.svg',
  Bedtime = '/assets/icons/bedtime.svg',
  Delete = '/assets/icons/delete.svg',
  Edit = '/assets/icons/edit.svg',
  ExpandMore = '/assets/icons/expand-more.svg',
  History = '/assets/icons/history.svg',
  MoreVert = '/assets/icons/more-vert.svg',
  Note = '/assets/icons/note.svg',
  RemoveCircle = '/assets/icons/remove-circle.svg',
  Straighten = '/assets/icons/straighten.svg',
  WaterDrop = '/assets/icons/water-drop.svg',
  Weight = '/assets/icons/weight.svg',
}
